name: halalfood
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter_bloc: 8.1.3
  equatable: 2.0.5
  flutter_screenutil: 5.8.4
  json_annotation: 4.8.1
  dartz: 0.10.1
  retrofit: 4.0.1
  dio: 5.2.1  
  mockito: 5.4.2
  go_router: 9.0.2
  json_serializable: 6.7.1
  flash: 3.0.5+1
  get_it: 7.6.0
  flutter_easyloading: 3.0.5
  shared_preferences: 2.2.0
  flutter_svg: 2.0.7
  flutter_dotenv: 5.1.0
  bloc_test:  9.1.3
  http_mock_adapter: 0.4.4
  google_fonts: 5.1.0
  intl: 0.18.0
  rxdart: 0.27.7
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner:
  retrofit_generator: 7.0.8
  mock_web_server: 5.0.0-nullsafety.1
  meta:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/
 

